import {test,expect} from '@playwright/test';

test('end to end testing',async({page})=>{

await page.goto('https://opensource-demo.orangehrmlive.com/web/index.php/auth/login');

//await expect (page.getByRole('img',{name:'OrangHrm'})).toBeVisible();


//login page
await page.getByPlaceholder('Username').fill('Admin');
await page.getByRole('textbox',{name:'Password'}).fill('admin123');
await page.getByRole('button',{name:'Login'}).click();

await expect (page.getByRole('heading',{name:'Dashboard'})).toBeVisible();

await page.getByRole('link',{name:'PIM'}).click();

await expect (page.getByRole('heading',{name:'PIM'})).toBeVisible();

await expect(page).toHaveURL('https://opensource-demo.orangehrmlive.com/web/index.php/pim/viewEmployeeList');

//add employee
await page.getByRole('button',{name:'Add'}).click();

await page.waitForLoadState('load');
await expect(page.getByText('Employee Full Name')).toBeVisible();

await page.getByPlaceholder('First Name').fill('Ravi');
await page.getByPlaceholder('Middle Name').fill('Kumar');
await page.getByPlaceholder('Last Name').fill('Sharma');


const employeeID=page.locator('.oxd-input-group').filter({has:page.locator('label',{hasText:'Employee Id'})}).locator('.oxd-input.oxd-input--active')

const employeeIDValue=await employeeID.inputValue();

console.log("Autogenerated Employee ID is: ",employeeIDValue);

await page.getByRole('button',{name:'Save'}).click();

await expect(page.getByRole('heading',{name:'Personal Details'})).toBeVisible({timeout:3000}); //validation

//again click on PIM link 
await page.getByRole('link',{name:'PIM'}).click();

await employeeID.fill(employeeIDValue);
await page.getByRole('button',{name:'Search'}).click();

const newEmployeeRow=page.locator('.oxd-table-card').filter({hasText:employeeIDValue});

await newEmployeeRow.click();

page.locator('.oxd-input-group').filter({has:page.locator('label',{hasText:"Driver's License Number"
})}).locator('.oxd-input oxd-input--active').fill('DL123');

page.locator('.oxd-input-group').filter({has:page.locator('label',{hasText:"Driver's License Number"
})}).getByPlaceholder('yyyy-mm-dd').fill('2026-12-31');//calender for licenceexpiry date

//calender for date of birth
const calender=page.locator('.oxd-input-group').filter({has:page.locator('label',{hasText:"Date of Birth"})}).getByPlaceholder('yyyy-dd-mm');
await calender.click();

const year='1993';
const month='jan';
const date='22';

const calenderdropdown=page.locator('.oxd-date-input-calender')

await calenderdropdown.waitFor({state:'visible',timeout:1500});

await calenderdropdown.getByText('2026').click();

await calenderdropdown.getByText(year).click();

await calenderdropdown.getByText('September').click();

await calenderdropdown.getByText(month).click();

await calenderdropdown.getByText(date).click();
await expect(calender).toHaveValue('1993-22-jan');
})
